---
- name: Configure new servers
  hosts: all_servers
  become: true
  gather_facts: true

  roles:
    - role: common
    - role: user
    - role: security
    - { role: docker, when: install_docker | default(false) }
