---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    force_apt_get: true

- name: Install essential packages
  ansible.builtin.package:
    name:
      - curl
      - vim
      - git
      - htop
      - apt-transport-https
      - ca-certificates
      - neofetch
    state: present
    update_cache: true

- name: Ensure Python 3 and passlib are installed
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
      - python3-passlib
    state: present
